x = int(input('Enter number in miles to convert to kilometers: '))
print(x*1.60934)
y = int(input('Enter number of square feet to convert to square meters: '))
print(y*.092903)
z = int(input('Enter number in years to convert to seconds: '))
print(z*60*60*24*365)
